## TP of Mr.cheragui held by Mr.moulay lakhdar
### ACP TP
#### by abdedaiem amin

In [1]:
import math
import numpy as np
import math as m

import scipy.linalg
import sympy
from sympy import *
from sympy.solvers import solve
from sympy import Symbol
from scipy import *
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.decomposition import PCA
lamda = Symbol("lamda")
a = Symbol("a")
b = Symbol("b")
c = Symbol("c")

In [2]:
matrice = np.array([[1 , 2 ],[ 8 , 9]])
matrice2 = np.array([[1 , 2 , 1] , [0 , 1 , 0] , [ 1 , 0  ,1 ] ])
file = pd.read_csv("TP_CHERAGUI.csv")

In [3]:
DATA = pd.DataFrame(file)
DATA

CAR  LEC  GEA
0   10    6    8
1    6   11   10
2   12   13    8
3   12   10   14

In [4]:
DATA = np.array(DATA)
DATA

array([[10,  6,  8],
       [ 6, 11, 10],
       [12, 13,  8],
       [12, 10, 14]])

In [5]:
class ACPNonNorme():
    def __init__(self, matrice):
        self.matrice = matrice

    def CalcBARS(self,matrice , elements):
        CAR_bar , LEC_bar , GEA_bar = 0,0,0
        for i in range(len(matrice[0]) + 1):
            CAR_bar += matrice[i][0]
            LEC_bar += matrice[i][1]
            GEA_bar += matrice[i][2]
        sums = [CAR_bar , LEC_bar , GEA_bar]
        return round(CAR_bar/ elements , 2) , round(LEC_bar/ elements , 2) , round(GEA_bar/ elements , 2) , sums

    def CalcMatriceCenter(self,matrice , elements , sums):
        Xij =  list()
        for i in range(len(matrice)):
            temp = list()
            for j in range(len(matrice[i])):
                temp.append(round((matrice[i][j] - sums[0]/4), 2))
            Xij.append(temp)
        return np.array(Xij)

    def CalcMatriceV(self,V):
        return 1/len(V) * V.T.dot(V)

    def return_DET_matricx(self, V):
        identifier = np.array([[1,0,0] , [0,1,0] , [0,0,1]])
        return V - lamda*identifier

    def return_V(self, V , sol):
        identifier = np.array([[sol,0,0] , [0,sol,0] , [0,0,sol]])
        return V - sol*identifier


    def make_equations(self,V):
        n = list()
        for row in V:
            n.append(row)
        return n
class ACPNorme():
    pass

def moyan(array):
    return 1/len(array) * sum(array[x] for x in range(len(array)))

def var(array , moy):
    res = 0
    for a in array:
        res += math.pow((a - moy), 2)
    return 1/len(array) *  res

def cov(array1 , array2, moy , moy2):
    res = 0
    for i in range(len(array1)):
        res += (array1[i] - moy) * (array2[i] - moy2)
    return 1/len(array1) * res

def cor(convXY , varX , varY):
    return convXY / (math.sqrt(varX)*math.sqrt(varY))

In [6]:
test = ACPNonNorme(DATA)

In [7]:
# prints the matrice center
CAR_bar , LEC_bar , GEA_bar , sums= test.CalcBARS(DATA , 4)
center = test.CalcMatriceCenter(DATA , 4 , sums)

In [8]:
pd.DataFrame(center)

0    1    2
0  0.0 -4.0 -2.0
1 -4.0  1.0  0.0
2  2.0  3.0 -2.0
3  2.0  0.0  4.0

In [9]:
# prints the matrice V
V = test.CalcMatriceV(center)
V

array([[6. , 0.5, 1. ],
       [0.5, 6.5, 0.5],
       [1. , 0.5, 6. ]])

In [10]:
equation = test.return_DET_matricx(V)

In [11]:
equation

array([[6.0 - lamda, 0.500000000000000, 1.00000000000000],
       [0.500000000000000, 6.5 - lamda, 0.500000000000000],
       [1.00000000000000, 0.500000000000000, 6.0 - lamda]], dtype=object)

In [12]:
r = sympy.Matrix(equation)

In [13]:
matrice_det = r.det()
matrice_det

-1.0*lamda**3 + 18.5*lamda**2 - 112.5*lamda + 225.0

In [14]:
solutions = solve(matrice_det)

In [15]:
solutions

[5.00000000000000, 6.00000000000000, 7.50000000000000]

In [16]:
best_solution = max(x for x in solutions)
best_solution

7.50000000000000

In [17]:
first_percentage = (solutions[2] / sum(solutions) ) * 100
print(str(floor(first_percentage)) + "%")
second_percentage = ((solutions[2] + solutions[1]) / sum(solutions)) * 100
print(str(floor(second_percentage)) + "%")
third_percentage = (((solutions[2] + solutions[1])  + solutions[0]) / sum(solutions) )* 100
print(floor(third_percentage))

40%
72%
100


In [18]:
new_V = test.return_V(V,solutions[2])

In [19]:
zeros = np.array([0,0,0])

In [20]:
new_V

array([[-50.2500000000000, 0.500000000000000, 1.00000000000000],
       [0.500000000000000, -49.7500000000000, 0.500000000000000],
       [1.00000000000000, 0.500000000000000, -50.2500000000000]],
      dtype=object)

In [21]:
new_V = np.array(new_V , dtype=float)

In [23]:
V

array([[6. , 0.5, 1. ],
       [0.5, 6.5, 0.5],
       [1. , 0.5, 6. ]])

In [27]:
val , vec = np.linalg.eigh(V)

In [28]:
val

array([5. , 6. , 7.5])

In [29]:
vec

array([[ 7.07106781e-01,  4.08248290e-01, -5.77350269e-01],
       [-7.00086403e-16, -8.16496581e-01, -5.77350269e-01],
       [-7.07106781e-01,  4.08248290e-01, -5.77350269e-01]])